[build]
  functions = "netlify/functions"
  command = "python3 -m pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.11"
  publish = "."

[functions]
  node_bundler = "esbuild"